// Editorial "what buyers actually shop for" hints, per country — the finished
// cultural products, never the raw materials (William, 2026-07-08: "me as a
// buyer, if I'm looking to shop in China I'm gonna look for things that are
// oriental, culture"). Raw materials stay in lib/specialities.ts as the
// internal lattice taxonomy; THESE strings are what renders on country cards.
//
// Rules for this list:
// - Product-level and culture-first: "Porcelain tea sets", not "Clay".
// - Recruitment copy only — NEVER rendered as a claim that sellers exist.
//   Live status always comes from /api/lattice.
// - No protected geographical indications used loosely, no weapons, no
//   restricted-material products (ivory, coral, shell) as hints.
// - Countries without a confident entry simply show name + flag + status.

export const CULTURE_HINTS: Record<string, string[]> = {
  // Asia
  CN: ['Porcelain tea sets', 'Silk robes', 'Calligraphy sets', 'Paper lanterns'],
  JP: ['Hand-forged kitchen knives', 'Matcha bowls', 'Washi stationery', 'Incense'],
  KR: ['Skincare', 'Celadon ceramics', 'Fermented pantry'],
  IN: ['Block-printed bedding', 'Brass homeware', 'Spice boxes', 'Silk scarves'],
  TH: ['Thai silk', 'Celadon ware', 'Curry pastes'],
  VN: ['Lacquer bowls', 'Silk lanterns', 'Robusta coffee'],
  ID: ['Batik sarongs', 'Rattan homeware', 'Teak carvings'],
  MY: ['Batik', 'Pewter ware'],
  PH: ['Handwoven textiles', 'Barako coffee'],
  KH: ['Silk kramas', 'Silverware'],
  LA: ['Handwoven silk', 'Mountain coffee'],
  MM: ['Lacquerware', 'Longyi textiles'],
  BD: ['Jamdani muslin', 'Jute homeware'],
  LK: ['Ceylon tea', 'Spice blends', 'Batik'],
  NP: ['Singing bowls', 'Lokta paper', 'Pashmina shawls', 'Copperware'],
  PK: ['Salt lamps', 'Onyx ware', 'Embroidered textiles'],
  MN: ['Cashmere knitwear', 'Felt boots'],
  KZ: ['Felt & leather goods'],
  KG: ['Shyrdak felt rugs'],
  UZ: ['Ikat silks', 'Suzani embroidery', 'Ceramics'],
  TJ: ['Embroidered textiles'],
  AM: ['Carpets', 'Pomegranate ceramics'],
  AZ: ['Carpets', 'Tea sets'],
  GE: ['Cloisonné jewellery', 'Fermented pantry'],
  AF: ['Kilim rugs', 'Lapis jewellery'],
  IR: ['Persian rugs', 'Saffron', 'Enamelware'],
  IQ: ['Dates', 'Copperware'],
  TR: ['Copper cezves', 'Kilim rugs', 'Hammam towels', 'Iznik ceramics'],
  SY: ['Aleppo soap', 'Marquetry boxes'],
  LB: ['Olive oil soap', 'Preserves'],
  IL: ['Dead Sea skincare', 'Olive wood carving'],
  JO: ['Dead Sea salts', 'Mosaic art'],
  SA: ['Dates', 'Oud perfume'],
  AE: ['Oud perfume', 'Dates'],
  OM: ['Frankincense', 'Perfume oils'],
  YE: ['Mocha coffee', 'Sidr honey'],
  QA: ['Oud & bakhoor'],
  KW: ['Dates', 'Perfume oils'],
  BH: ['Pearl jewellery'],
  TW: ['High-mountain oolong', 'Ceramics'],
  HK: ['Tea ware'],
  SG: ['Kaya & pantry', 'Peranakan ceramics'],
  BN: ['Woven songket'],
  BT: ['Woven textiles', 'Incense'],
  MV: ['Lacquer boxes'],
  TL: ['Tais weaving', 'Coffee'],
  // Africa
  MA: ['Leather babouches', 'Brass lanterns', 'Argan oil', 'Zellige tables'],
  TN: ['Olive oil', 'Fouta towels', 'Ceramic bowls'],
  EG: ['Hand-blown glass', 'Brass trays', 'Cotton linens'],
  ET: ['Coffee ceremony sets', 'Single-origin coffee'],
  KE: ['Kenyan tea', 'Beaded jewellery', 'Soapstone carvings'],
  TZ: ['Coffee', 'Maasai beadwork', 'Tingatinga art'],
  UG: ['Coffee', 'Bark cloth', 'Baskets'],
  RW: ['Agaseke peace baskets', 'Coffee'],
  NG: ['Adire indigo cloth', 'Beadwork'],
  GH: ['Kente cloth', 'Single-origin cacao', 'Recycled-glass beads'],
  CI: ['Cacao', 'Wax-print fashion'],
  SN: ['Baskets', 'Wax-print accessories'],
  ML: ['Mudcloth (bogolan)', 'Instruments'],
  BF: ['Bronze casting', 'Woven cotton'],
  ZA: ['Zulu baskets', 'Rooibos tea', 'Beadwork'],
  ZW: ['Shona stone sculpture', 'Baskets'],
  BW: ['Woven baskets'],
  NA: ['Karakul wool weaving'],
  MZ: ['Cashew & pantry', 'Capulana cloth'],
  MG: ['Vanilla', 'Raffia work'],
  MU: ['Vanilla tea', 'Model ships'],
  SC: ['Vanilla', 'Coco-de-mer motifs'],
  CM: ['Coffee', 'Beadwork'],
  CD: ['Coffee', 'Raffia textiles'],
  SD: ['Hibiscus & spices'],
  DZ: ['Berber rugs', 'Dates'],
  LY: ['Dates', 'Copperware'],
  // Europe
  IT: ['Leather bags', 'Murano glass', 'Olive oil', 'Tailoring'],
  FR: ['Perfume', 'Copper cookware', 'Linen', 'Preserves'],
  ES: ['Espadrilles', 'Olive oil', 'Ceramics', 'Saffron'],
  PT: ['Cork goods', 'Azulejo tiles', 'Filigree jewellery'],
  GR: ['Olive oil', 'Honey', 'Ceramics'],
  GB: ['Tailoring', 'Wool knitwear', 'Marmalade & preserves'],
  IE: ['Aran knitwear', 'Irish linen', 'Celtic jewellery'],
  DE: ['Kitchen knives', 'Optics', 'Christmas ornaments'],
  CH: ['Watches', 'Chocolate'],
  AT: ['Crystal glassware', 'Loden wool'],
  NL: ['Delftware pottery', 'Cheese'],
  BE: ['Chocolate', 'Lace'],
  SE: ['Glassware', 'Dala horses', 'Outdoor knives'],
  FI: ['Puukko knives', 'Design glassware'],
  DK: ['Design furniture', 'Ceramics'],
  NO: ['Norwegian knitwear'],
  IS: ['Lopapeysa knitwear', 'Flaky sea salt'],
  PL: ['Amber jewellery', 'Bolesławiec pottery'],
  CZ: ['Bohemian crystal', 'Marionettes'],
  SK: ['Wire art', 'Sheep cheese pantry'],
  HU: ['Embroidered linens', 'Paprika', 'Porcelain'],
  RO: ['Painted ceramics', 'Wool rugs'],
  BG: ['Rose oil', 'Ceramics'],
  RS: ['Wool knits', 'Preserves'],
  HR: ['Lavender & oils', 'Cravats'],
  SI: ['Beehive art', 'Salt pans'],
  UA: ['Vyshyvanka embroidery', 'Ceramics'],
  BY: ['Linen goods'],
  RU: ['Matryoshka dolls', 'Khokhloma ware'],
  LT: ['Amber jewellery', 'Linen'],
  LV: ['Amber jewellery', 'Wool mittens'],
  EE: ['Knitwear', 'Juniper ware'],
  MT: ['Filigree jewellery', 'Blown glass'],
  CY: ['Halloumi pantry', 'Lace'],
  AL: ['Filigree', 'Wool rugs'],
  MK: ['Filigree jewellery'],
  BA: ['Copper coffee sets'],
  ME: ['Olive oil'],
  MD: ['Ceramics', 'Preserves'],
  // The Americas
  MX: ['Talavera pottery', 'Barro negro', 'Embroidered huipiles', 'Copper pans'],
  GT: ['Woven huipiles', 'Jade jewellery', 'Coffee'],
  PE: ['Alpaca knitwear', 'Silver jewellery', 'Andean textiles'],
  BO: ['Alpaca throws', 'Aguayo weavings'],
  EC: ['Panama hats', 'Single-origin cacao'],
  CO: ['Coffee', 'Mochila bags', 'Emerald jewellery'],
  BR: ['Coffee', 'Gemstone jewellery', 'Hammocks'],
  AR: ['Leather goods', 'Mate gourds', 'Ponchos'],
  CL: ['Copper homeware', 'Lapis lazuli jewellery'],
  UY: ['Wool throws', 'Mate ware'],
  PY: ['Ñandutí lace'],
  VE: ['Single-origin cacao'],
  CU: ['Guayabera shirts', 'Coffee'],
  DO: ['Larimar jewellery', 'Cacao'],
  HT: ['Steel-drum art', 'Vetiver oil'],
  JM: ['Blue Mountain coffee', 'Spices'],
  TT: ['Steelpan instruments', 'Cacao'],
  CA: ['Maple syrup', 'Wool blankets'],
  US: ['Workwear denim', 'Craft leather', 'Hot sauce'],
  CR: ['Coffee', 'Oxcart-painted ware'],
  PA: ['Mola textiles', 'Geisha coffee'],
  NI: ['Coffee', 'Hammocks'],
  HN: ['Coffee', 'Lenca pottery'],
  SV: ['Coffee', 'Indigo textiles'],
  BZ: ['Cacao', 'Hot sauce'],
  // Oceania
  AU: ['Merino wool', 'Eucalyptus honey', 'Indigenous art'],
  NZ: ['Mānuka honey', 'Merino knitwear', 'Wood carving'],
  FJ: ['Masi bark cloth', 'Coconut skincare'],
  WS: ['Siapo cloth', 'Coconut oil'],
  TO: ['Ngatu bark cloth'],
  PG: ['Bilum bags', 'Coffee'],
  SB: ['Wood carving'],
  VU: ['Wood carving'],
}

export function cultureHints(code: string): string[] {
  return CULTURE_HINTS[code] ?? []
}
