// Editorial "what buyers actually shop for" hints, per country -- the finished
// cultural products, never the raw materials (William, 2026-07-08: "me as a
// buyer, if I'm looking to shop in China I'm gonna look for things that are
// oriental, culture"). Raw materials stay in lib/specialities.ts as the
// internal lattice taxonomy; THESE strings are what renders on country cards.
//
// Rules for this list:
// - Product-level and culture-first: "Porcelain tea sets", not "Clay".
// - Recruitment copy only -- NEVER rendered as a claim that sellers exist.
//   Live status always comes from /api/lattice.
// - No protected geographical indications used loosely, no weapons, no
//   restricted-material products (ivory, coral, shell) as hints.
// - Countries without a confident entry simply show name + flag + status.
//
// 2026-07-16 full rewrite: every one of the 190 site countries now has a
// researched, ranked "top 8 most iconic" list (fewer only where a country
// genuinely doesn't have 8 distinct, verifiable, on-rule products -- never
// padded). Sourced from two passes merged together: (1) 19 parallel research
// batches covering all 190 countries this session, each instructed to verify
// against real sources (Wikipedia, UNESCO ICH listings, tourism boards,
// craft/travel journalism) and rank most-iconic-first; (2) the richer,
// previously-approved mobile app dataset (mobile/src/data/hints.ts,
// "Generated from the approved Atlas mockup"), recovered from git history
// after an automated commit accidentally deleted the mobile/ app, and used
// here as the primary source where it had deeper coverage. Duplicates
// collapsed, and every restricted-material or weapon hit the merge surfaced
// (capiz/conch/paua shell, shell money, coral, a "vegetable ivory" mention,
// Yemeni jambiya daggers) was individually reviewed and either dropped or
// honestly rephrased -- coconut-shell craft was kept as a plant byproduct,
// not a restricted marine material, consistent with wood/bamboo entries
// elsewhere in this file.

export const CULTURE_HINTS: Record<string, string[]> = {
  // Asia
  CN: ['Porcelain tea sets', 'Blue-and-white vases', 'Silk robes & qipao', 'Jade jewellery', 'Cloisonné ware', 'Yixing clay teapots', 'Gongfu tea ware', 'Calligraphy & ink brushes'],
  JP: ['Hand-forged kitchen knives', 'Matcha & tea bowls', 'Cast-iron teapots (tetsubin)', 'Washi paper & stationery', 'Kintsugi repair kits', 'Incense', 'Sake sets', 'Kokeshi dolls'],
  KR: ['K-beauty skincare', 'Celadon ceramics', 'Moon jars', 'Hanji paper goods', 'Najeon lacquerware (mother-of-pearl)', 'Bojagi wrapping cloth', 'Fermented pantry (kimchi, gochujang)', 'Onggi jars'],
  IN: ['Block-printed textiles', 'Silk saris & scarves', 'Brass & bell-metal homeware', 'Spice boxes & masala', 'Kashmiri pashmina shawls', 'Marble inlay (pietra dura)', 'Jaipur blue pottery', 'Kundan & jhumka jewellery'],
  TH: ['Thai silk', 'Celadon ceramics', 'Benjarong porcelain', 'Curry pastes', 'Bronzeware & cutlery', 'Spa & aromatherapy', 'Rattan & wicker bags', 'Khon masks'],
  VN: ['Lacquerware', 'Silk lanterns', 'Robusta coffee & phin filters', 'Bat Trang ceramics', 'Conical hats (non la)', 'Ao dai silk', 'Bamboo & rattan homeware', 'Embroidered art'],
  ID: ['Batik textiles', 'Rattan homeware', 'Teak & Bali wood carving', 'Silver (Bali/Yogya) jewellery', 'Ikat weaving', 'Songket brocade', 'Wayang puppets', 'Kopi luwak & coffee'],
  MY: ['Pewter ware', 'Batik textiles', 'Songket brocade', 'Peranakan ceramics', 'Rattan & mengkuang weaving', 'Brass & silver metalwork', 'White coffee', 'Wood carving'],
  PH: ['Piña & abaca handwoven textiles', 'Barako coffee', 'Rattan & wicker furniture', 'Woven baskets', 'Wood carving', 'Pearl jewellery', 'Banig mats', "T'nalak abaca cloth"],
  KH: ['Silk kramas & ikat', 'Silverware', 'Kampot pepper', 'Palm-sugar pantry', 'Stone & wood carving', 'Woven baskets', 'Krama scarves', 'Kbach carving'],
  LA: ['Handwoven silk (sinh)', 'Bolaven mountain coffee', 'Sa (mulberry) paper', 'Silverware', 'Rattan & bamboo craft', 'Natural-dye textiles', 'Hill-tribe silver'],
  MM: ['Lacquerware', 'Longyi & Chin textiles', 'Jade jewellery', 'Gold-leaf craft', 'Thanaka skincare', 'Marionette puppets', 'Parasols', 'Silver ware'],
  BD: ['Jamdani muslin', 'Jute homeware & bags', 'Nakshi kantha quilts', 'Pink pearl', 'Rickshaw art', 'Cane & bamboo craft', 'Terracotta pottery', 'Silk (Rajshahi)'],
  LK: ['Ceylon tea', 'Cinnamon & spice blends', 'Batik textiles', 'Blue sapphires & gems', 'Handloom cotton', 'Wood masks', 'Coir & coconut craft', 'Brass ware'],
  NP: ['Singing bowls', 'Lokta paper goods', 'Pashmina shawls', 'Copper & brass ware', 'Thangka painting', 'Felt wool crafts', 'Khukuri knives', 'Prayer flags & beads'],
  PK: ['Himalayan salt lamps', 'Onyx & marble ware', 'Embroidered textiles (phulkari)', 'Blue pottery (Multan)', 'Truck-art decor', 'Leather goods', 'Camel-skin lamps', 'Ralli quilts'],
  MN: ['Cashmere knitwear', 'Felt (wool) goods', 'Leather boots', 'Horsehair crafts', 'Silver ornaments', 'Deel robes', 'Nomadic saddlery', 'Ger (yurt) textiles'],
  KZ: ['Felt (shyrdak) & leather goods', 'Silver jewellery', 'Camel & sheep wool crafts', 'Woven wall hangings (tuskiiz)', 'Horsehair & saddlery', 'Kumis ware', 'Tekemet & syrmak felt', 'Dombra instruments'],
  KG: ['Shyrdak felt rugs', 'Ala-kiyiz felt art', 'Yurt textiles', 'Leather & silver craft', 'Wool crafts', 'Kalpak & felt hats'],
  UZ: ['Ikat silks (adras)', 'Suzani embroidery', 'Rishton ceramics', 'Chust knives', 'Gold embroidery', 'Miniature painting', 'Copper ware', 'Silk carpets'],
  TJ: ['Atlas & adras silks', 'Embroidered textiles (chakan)', 'Skullcaps (tubeteika)', 'Pamiri wool socks', 'Wood carving', 'Copperware', 'Chakan embroidery', 'Suzani wall hangings'],
  TM: ['Hand-knotted Turkmen carpets', 'Silver & carnelian jewellery', 'Telpek wool hats', 'Silk (keteni) textiles', 'Embroidery', 'Turkmen felt rugs', 'Embroidered skullcaps'],
  AM: ['Carpets & rugs', 'Pomegranate-motif ceramics', 'Silver & filigree jewellery', 'Obsidian craft', 'Khachkar stone motifs', 'Apricot-wood duduk', 'Dried fruit & pantry', 'Duduk & instruments'],
  AZ: ['Carpets & rugs', 'Copper ware', 'Tea sets & armudu glasses', 'Pomegranate crafts', 'Sheki inlay (shebeke)', 'Kelaghayi silk scarves', 'Sheki shebeke glass'],
  GE: ['Cloisonné (minankari) jewellery', 'Qvevri wine & ware', 'Felt (namtari) crafts', 'Enamel art', 'Silverwork', 'Churchkhela & pantry', 'Wool carpets', 'Cha-cha & wine ware'],
  AF: ['Kilim & war rugs', 'Lapis lazuli jewellery', 'Hand-knotted carpets', 'Embroidered dresses', 'Copperware', 'Pomegranate & saffron', 'Blue pottery (Istalif)', 'Karakul hats'],
  IR: ['Persian hand-knotted rugs', 'Saffron', 'Enamel (mina) ware', 'Termeh brocade', 'Khatam marquetry', 'Turquoise (Firoozeh) jewellery', 'Copper & engraving (ghalamzani)', 'Rosewater & pantry'],
  IQ: ['Dates & date syrup', 'Copperware', 'Reed (marsh) craft', 'Handwoven rugs', 'Silver jewellery', 'Brass trays', 'Arabic calligraphy art', 'Najaf agate rings'],
  TR: ['Copper cezves & ware', 'Kilim & Turkish rugs', 'Hammam (peshtemal) towels', 'Iznik ceramics', 'Evil-eye (nazar) glass', 'Turkish delight & pantry', 'Mosaic lamps', 'Olive-oil soap'],
  SY: ['Aleppo laurel soap', 'Damascene marquetry (wood inlay)', 'Brocade (damask) textiles', 'Mosaic boxes', 'Brass & copper ware', 'Glass-blowing', 'Rosewater & pantry', 'Aghabani embroidery'],
  LB: ['Olive-oil soap', 'Blown glass', "Preserves & pantry (za'atar)", 'Rosewater & orange blossom', 'Copperware', 'Embroidery', 'Ceramics', 'Copper artwork (lamps & kettles)'],
  IL: ['Dead Sea skincare', 'Olive-wood carving', 'Silver Judaica', 'Pomegranate motifs', 'Hamsa jewellery', 'Date honey (silan)', 'Armenian ceramic tiles'],
  JO: ['Dead Sea salts & mud', 'Mosaic art', 'Sand-art bottles', 'Olive-wood & mother-of-pearl', 'Embroidery', 'Nabatean-motif silver', 'Bedouin rugs', 'Jordanian silver jewellery'],
  SA: ['Dates & date sweets', 'Oud & bakhoor', 'Attar perfume oils', 'Sadu Bedouin weaving', 'Silver & Najdi jewellery', 'Coffee (qahwa) ware', 'Frankincense'],
  AE: ['Oud & attar perfume', 'Dates & date sweets', 'Bakhoor & incense', 'Camel-leather goods', 'Sadu weaving', 'Gold jewellery', 'Arabic coffee ware', 'Khoos palm weaving'],
  OM: ['Frankincense & resin', 'Perfume & attar oils', 'Silver khanjar & jewellery', 'Rosewater (Jebel Akhdar)', 'Halwa & pantry', 'Bahla pottery', 'Camel-wool textiles', 'Frankincense & bakhoor'],
  YE: ['Mocha coffee', 'Sidr honey', 'Silver filigree jewellery', 'Woven textiles', 'Dhurra pottery', 'Frankincense resin', 'Yemeni raisins'],
  QA: ['Oud & bakhoor', 'Attar perfume oils', 'Pearl jewellery', 'Sadu weaving', 'Dates & pantry', 'Arabic coffee ware', 'Hand-woven bisht cloaks', 'Gold & silver-thread naqdah embroidery'],
  KW: ['Dates & sweets', 'Perfume & oud oils', 'Sadu Bedouin weaving', 'Pearl jewellery', 'Dhow-craft models', 'Bukhoor', 'Al Sadu woven textiles', 'Dallah coffee pots'],
  BH: ['Natural pearl jewellery', 'Gold craft', "Pottery (A'ali)", 'Basket & palm weaving', 'Oud & perfume', 'Dates', 'Al-Sadu Bedouin woven textiles', 'Palm-frond basketware'],
  TW: ['High-mountain oolong tea', 'Gongfu tea ware', 'Ceramics (Yingge)', 'Pineapple cake & pantry', 'Bubble-tea culture', 'Lacquer & woodcraft', 'Glove puppetry crafts', 'Hand-pulled noodle tools'],
  HK: ['Tea ware', 'Milk-tea culture', 'Enamelware', 'Chops & seal carving', 'Tailoring & bespoke shirts', 'Neon-sign craft', 'Dim sum steamers', 'Hand-carved mahjong tiles'],
  SG: ['Peranakan ceramics & tiles', 'Kaya & kopi pantry', 'Batik & sarong craft', 'Tailoring', 'Orchid & botanical scents', 'Nyonya beadwork', 'Beaded Peranakan slippers (kasut manik)', 'Bak kwa barbecued meat jerky'],
  MO: ['Almond cookies', 'Portuguese-style egg tarts', 'Pastelaria pantry', 'Hand-painted azulejo motifs', 'Jerky (bak kwa)', 'Macau peanut candy', 'Handcrafted incense sticks', 'Macau herbal tea blends'],
  BN: ['Songket brocade', 'Silverwork & brass', 'Woven baskets', 'Woodcraft', 'Silver jewellery & ceremonial silverware', 'Handwoven rattan dish covers (Tudung Dulang)', 'Songkok caps'],
  BT: ['Handwoven textiles (kira)', 'Incense', 'Wood carving', 'Thangka painting', 'Bamboo craft', 'Handmade paper', 'Silver jewellery', 'Wooden masks'],
  MV: ['Lacquer boxes (liye laa jehun)', 'Coir rope craft', 'Woven mats (thundu kunaa)', 'Reef-safe skincare', 'Coconut oil', 'Miniature dhoni boat models', 'Kasabu embroidered textiles', 'Traditional gold and silver jewellery'],
  TL: ['Tais handwoven textiles', 'Single-origin coffee', 'Woven baskets', 'Wood carving', 'Hand-painted pottery'],
  // Africa
  MA: ['Leather babouches & poufs', 'Brass & pierced-metal lanterns', 'Argan oil', 'Zellige-tiled tables', 'Tagines & pottery', 'Berber rugs & kilims', 'Mint-tea sets', 'Kaftans & djellabas'],
  TN: ['Olive oil & pantry', 'Fouta towels', 'Nabeul ceramics', 'Berber & Kairouan rugs', 'Birdcage (Sidi Bou Said) craft', 'Silver jewellery', 'Harissa & spice pantry', 'Leather goods'],
  EG: ['Hand-blown (muski) glass', 'Brass & copper trays', 'Egyptian cotton linens', 'Papyrus art', 'Alabaster ware', 'Khayamiya appliqué', 'Perfume bottles & oils', 'Backgammon boards'],
  ET: ['Coffee-ceremony sets', 'Single-origin coffee', 'Jebena coffee pots', 'Habesha woven dresses', 'Mesob baskets', 'Berbere spice', 'Teff & pantry', 'Ethiopian-cross jewellery'],
  KE: ['Maasai beadwork', 'Kenyan tea & coffee', 'Soapstone (kisii) carving', 'Kiondo sisal baskets', 'Kikoy & kanga textiles', 'Wood & animal carving', 'Leather sandals (akala)', 'Shuka blankets'],
  TZ: ['Tingatinga painting', 'Maasai beadwork', 'Zanzibar spices', 'Kanga & kitenge textiles', 'Makonde ebony carving', 'Tanzanite jewellery', 'Woven baskets', 'Coffee & pantry'],
  UG: ['Bark cloth', 'Coiled (raffia) baskets', 'Coffee', 'Beaded (paper) jewellery', 'Wood carving', 'Batik & kitenge textiles', 'Drums & instruments', 'Ankole cattle horn crafts'],
  RW: ['Agaseke peace baskets', 'Coffee', 'Imigongo cow-dung art', 'Beaded jewellery', 'Woven mats', 'Wood carving', 'Honey & pantry'],
  NG: ['Adire indigo textiles', 'Aso-oke handwoven cloth', 'Yoruba royal beadwork', 'Bronze (Benin) casting', 'Leather (Sokoto) goods', 'Calabash carving', 'Ankara wax-print fashion', 'Talking-drum instruments'],
  BJ: ['Abomey appliqué tapestries', 'Bronze & brass casting', 'Wood & mask carving', 'Woven baskets', 'Batik textiles', 'Beaded jewellery', 'Bocio wood-carved Vodun figures', 'Abomey lost-wax brass sculptures'],
  GH: ['Kente handwoven cloth', 'Single-origin cacao', 'Recycled-glass (Krobo) beads', 'Adinkra stamped prints', 'Shea butter', 'Bolga baskets', 'Djembe & drum instruments', 'Black soap'],
  SN: ['Coiled (Sahel) baskets', 'Wax-print & boubou fashion', 'Sous-verre glass painting', 'Sabar & djembe drums', 'Leather goods', 'Silver (Fulani) jewellery', 'Wood carving', 'Bissap & pantry'],
  GM: ['Batik & tie-dye textiles', 'Djembe & drum craft', 'Woven baskets', 'Wood carving', 'Silver & beaded jewellery', 'Leather goods', 'Kora (handcrafted 21-string harp)', 'Hand-thrown pottery (Brikama & Basse)'],
  ML: ['Bogolan mud-cloth', 'Kora & djembe instruments', 'Tuareg leather & silver', 'Fulani gold earrings', 'Woven blankets', 'Wood & mask carving', 'Pottery', 'Indigo textiles'],
  BF: ['Bronze (lost-wax) casting', 'Handwoven Faso Dan Fani cotton', 'Bogolan mud-cloth', 'Leather goods', 'Bronze & brass jewellery', 'Wood carving', 'Basketry', 'Wooden ceremonial masks'],
  GN: ['Djembe drums', 'Indigo & wax textiles', 'Leather goods', 'Wood & mask carving', 'Woven baskets', 'Silver jewellery', 'Baga Nimba masks', 'Leppi indigo-dyed cotton cloth (Fouta Djallon)'],
  SL: ['Gara tie-dye textiles', 'Country-cloth weaving', 'Wood & mask carving', 'Woven baskets', 'Beaded jewellery', 'Raffia craft', 'Hand-carved Sowei masks & figures', 'Contemporary studio pottery (Waterloo)'],
  TG: ['Kente & batik textiles', 'Bronze (lost-wax) casting', 'Wood & mask carving', 'Woven baskets', 'Beaded jewellery', 'Pottery', 'Wood carvings & statuary', 'Pyrography-decorated calabashes'],
  CV: ['Grogue sugarcane spirit', 'Handwoven (panu) baskets & cloth', 'Ceramics & pottery', 'Coffee & pantry', 'Coconut & shell craft', 'Batik textiles', 'Pontche spiced liqueur', 'Panu di Terra woven cloth'],
  ZA: ['Zulu beadwork & baskets', 'Rooibos tea', 'Ndebele-motif crafts', 'Wire & bead art', 'Springbok-leather goods', 'Ceramics & pottery', 'Shweshwe textiles', 'Wine & pantry'],
  ZW: ['Shona stone sculpture', 'Woven (Binga) baskets', 'Verdite & serpentine carving', 'Crocheted & wire craft', 'Beaded jewellery', 'Batik textiles', 'Copper & tin craft', 'Binga & Tonga baskets'],
  ZM: ['Emerald jewellery', 'Tonga & Gwembe baskets', 'Copper craft', 'Chitenge textiles', 'Wood & mask carving', 'Malachite craft', 'Honey & pantry', 'Bemba grass baskets'],
  BW: ['Coiled mokola baskets', 'Leather & hide goods', 'Beaded jewellery', 'Pottery', 'Wood carving', 'Ostrich-eggshell beads', 'San (Bushman) art & jewellery'],
  NA: ['Karakul wool weaving & rugs', 'Himba craft & ochre jewellery', 'Baskets & woven crafts', 'Leather goods', 'Semi-precious gemstones', 'Wood carving', 'Ostrich-eggshell beads'],
  LS: ['Basotho blankets', 'Mokorotlo woven hats', 'Mohair & wool textiles', 'Grass weaving', 'Beaded jewellery', 'Pottery', 'Wool tapestries', 'Mohair throws & knitwear'],
  SZ: ['Ngwenya recycled glassware', 'Sisal woven baskets', 'Batik & candle craft', 'Beaded jewellery', 'Wood carving', 'Mohair textiles', 'Grass mats', 'Swazi candles'],
  MW: ['Dedza pottery', 'Chitenje wax-print textiles', 'Wood carving', 'Woven (sisal) baskets', 'Beaded jewellery', 'Coffee & tea pantry', 'Cane furniture', 'Gule Wamkulu carved masks'],
  MZ: ['Capulana textiles', 'Cashew & pantry', 'Makonde ebony carving', 'Woven baskets', 'Beaded jewellery', 'Ceramics', 'Coconut craft', 'Piri-piri sauce'],
  MG: ['Vanilla', 'Raffia weaving & bags', 'Wild silk (landibe) textiles', 'Zafimaniry wood carving', 'Antaimoro paper', 'Semi-precious gemstones', 'Embroidery', 'Spices & pantry'],
  MU: ['Model ships', 'Vanilla tea & pantry', 'Sega & basketry craft', 'Textiles & cashmere', 'Rum & sugar pantry', 'Dodo-motif crafts', 'Sand-art bottles', 'Ravanne drums'],
  SC: ['Vanilla & pantry', 'Coco-de-mer craft', 'Coconut & shell craft', 'Batik & pareo textiles', 'Model-boat craft', 'Tea & spice pantry', 'Vacoa palm-leaf woven baskets & hats', 'Takamaka Bay rum'],
  KM: ['Ylang-ylang perfume oil', 'Vanilla & spices', 'Embroidered (kofia) caps', 'Woven baskets', 'Wood carving', 'Shiromani textiles', 'Cloves'],
  CM: ['Beaded (Bamileke) thrones & masks', 'Coffee & cacao', 'Toghu embroidered textiles', 'Wood & mask carving', 'Woven baskets', 'Bronze casting', 'Calabash craft'],
  CD: ['Kuba raffia cloth', 'Coffee', 'Wood & mask carving', 'Malachite & copper craft', 'Woven baskets', 'Beaded jewellery', 'Ceramics', 'Congolese popular paintings'],
  GA: ['Mbigou stone carving', 'Wood & mask carving', 'Woven baskets', 'Raffia textiles', 'Beaded jewellery', 'Ebony craft', 'Kota reliquary figures (mbulu ngulu)', 'Punu masks'],
  SD: ['Hibiscus (karkade) & spices', 'Silver & gold jewellery', 'Woven baskets & mats', 'Leather goods', 'Ebony & wood carving', 'Perfume oils', 'Pottery', 'Toub wrap garments (thobe sudani)'],
  MR: ['Tuareg silver jewellery', 'Malahfa embroidered textiles', 'Leather goods & cushions', 'Woven mats & baskets', 'Wooden bowls & spoons', 'Silver-and-ebony craft', 'Pottery', 'Boubou embroidered robes'],
  DZ: ['Berber rugs & textiles', 'Deglet Nour dates', 'Kabyle silver & enamel jewellery', 'Pottery & ceramics', 'Copperware', 'Leather goods', 'Basketry', 'Burnous wool cloaks'],
  LY: ['Dates & pantry', 'Copperware', 'Silver Tuareg jewellery', 'Handwoven textiles', 'Leather goods', 'Basketry', 'Palm-frond craft', 'Extra-virgin olive oil'],
  AO: ['Chokwe wood masks', 'Carved stools & thrones', 'Sisal basketry', 'Clay pottery', 'Beaded jewellery', 'Woven mats', 'Ironwork', 'Chokwe wooden statues'],
  BI: ['Coiled basketry', 'Ceremonial drums', 'Twa pottery', 'Wood carving', 'Beaded jewellery', 'Coffee & pantry'],
  LR: ['Patchwork quilts', 'Country-cloth weaving', 'Woven baskets', 'Soapstone carving', 'Beaded jewellery', 'Ceremonial wood masks', 'Figurative wood carvings'],
  TD: ['Leather goods', 'Tuareg silver jewellery', 'Hand-dyed textiles', 'Wood carving', 'Woven mats & baskets', 'Calabash craft', 'Pottery', 'Hand drums'],
  CF: ['Woven baskets', 'Wood & mask carving', 'Ebony craft', 'Bark cloth', 'Beaded jewellery', 'Ironwork', 'Raffia textiles', 'Likembe thumb pianos'],
  CG: ['Poto-Poto painting', 'Wood & mask carving', 'Raffia textiles', 'Woven baskets', 'Beaded jewellery', 'Ceramics', 'Carved ceremonial masks', 'Hand drums'],
  GW: ['Cashew nuts & pantry', 'Bijagós wood carving', 'Handwoven (pano) cloth', 'Woven baskets', 'Beaded jewellery', 'Pottery'],
  NE: ['Tuareg silver (Agadez cross)', 'Tuareg leather goods', 'Woven mats & baskets', 'Wood & calabash craft', 'Camel-leather craft', 'Indigo textiles', 'Hausa embroidered boubou robes', 'Decorated calabash carving'],
  SS: ['Beaded jewellery & corsets', 'Woven baskets', 'Ebony & wood carving', 'Leather goods', 'Gourd & calabash craft', 'Ironwork', 'Beaded wall hangings'],
  GQ: ['Fang wood masks', 'Woven raffia baskets', 'Beaded jewellery', 'Ebony carving', 'Bark-cloth craft', 'Pottery', 'Fang reliquary figures'],
  ER: ['Jebena coffee pots', 'Filigree silver jewellery', 'Woven (mesob) baskets', 'Handwoven cotton', 'Leather goods', 'Spice & coffee pantry', 'Silver cross pendants'],
  SO: ['Frankincense & myrrh', 'Woven (sisal) baskets', 'Meerschaum & wood craft', 'Silver & amber jewellery', 'Handwoven textiles', 'Leather goods', 'Camel-milk pantry', 'Somali incense burners'],
  DJ: ['Woven mats & baskets', 'Afar & Somali textiles', 'Silver jewellery', 'Leather goods', 'Frankincense', 'Wood & knife craft', 'Fouta striped cotton wraps', 'Dirac wraparound dress'],
  // Europe
  IT: ['Leather bags & goods', 'Murano glass', 'Olive oil & pantry', 'Bespoke tailoring', 'Hand-painted ceramics (maiolica)', 'Espresso & moka ware', 'Venetian masks', 'Silk ties & scarves'],
  FR: ['Perfume & fragrance', 'Copper cookware', 'Linen & table textiles', 'Preserves & mustard', 'Marseille & Savon soap', 'Lavender oils', 'Ceramics (Provence, Limoges)', 'Berets & Basque linen'],
  ES: ['Espadrilles', 'Olive oil & pantry', 'Ceramics & azulejo tiles', 'Saffron', 'Hand-held fans (abanicos)', 'Damascene (Toledo) jewellery', 'Paella pans', 'Turrón & confectionery'],
  PT: ['Cork goods', 'Azulejo tiles', 'Filigree jewellery', 'Tinned sardine pantry', 'Barcelos rooster crafts', 'Madeira embroidery', 'Ceramic swallows', 'Wool (Burel) blankets'],
  GR: ['Olive oil & olives', 'Honey & pantry', 'Ceramics & pottery', 'Komboloi worry beads', 'Byzantine icon art', 'Leather sandals', 'Herbs, oregano & mountain tea', 'Backgammon (tavli)'],
  GB: ['Bespoke tailoring', 'Wool & cashmere knitwear', 'Harris tweed', 'Marmalade & preserves', 'Teapots & fine bone china', 'Brogues & leather shoes', 'Flat caps', 'Wax jackets (Barbour)'],
  IE: ['Aran wool knitwear', 'Irish linen', 'Celtic & Claddagh jewellery', 'Belleek porcelain', 'Tweed caps & cloth', 'Whiskey & pantry', 'Bodhrán drums', 'Crystal (Waterford)'],
  DE: ['Kitchen knives (Solingen)', 'Optics & precision tools', 'Christmas ornaments', 'Cuckoo clocks', 'Beer steins', 'Nutcrackers & smokers', 'Enamel cookware', 'Leather goods'],
  CH: ['Watches & horology', 'Chocolate', 'Swiss army knives', 'Cowbells & alpine craft', 'Cheese (gruyère, raclette)', 'Music boxes', 'Embroidery (St. Gallen)', 'Precision tools'],
  AT: ['Crystal glassware (Swarovski)', 'Loden wool coats', 'Porcelain (Augarten)', 'Dirndl & trachten', 'Petit-point embroidery', 'Mozartkugel & confectionery', 'Snow globes', 'Woodcraft & nutcrackers'],
  LI: ['Collectible postage stamps', 'Precision ceramics', 'Alpine woodcraft', 'Wine ware', 'Air-dried ham & sausage specialities', 'Traditional folk costumes (Tracht)'],
  NL: ['Delftware pottery', 'Cheese (gouda, edam)', 'Tulip & bulb crafts', 'Wooden clogs', 'Stroopwafel pantry', 'Bicycle accessories', 'Licorice (drop)', 'Leather & design goods'],
  BE: ['Chocolate & pralines', 'Lace', 'Beer & brewing ware', 'Tapestry', 'Comic & poster art', 'Waffles & pantry', 'Diamonds (Antwerp)', 'Pewter & brass'],
  LU: ['Péckvillchen clay whistles', 'Porcelain (Villeroy & Boch)', 'Ironwork & pewter', 'Wine & crémant ware', 'Pastry & pantry', 'Artisanal handmade chocolates & pralines', 'Hand-turned wooden pens & accessories', 'Crystal glassware'],
  SE: ['Design glassware (Kosta, Orrefors)', 'Dala horses', 'Outdoor & sloyd knives', 'Sami craft (duodji)', 'Linen & textiles', 'Ceramics', 'Candles & pantry', 'Wool blankets'],
  FI: ['Puukko knives', 'Design glassware (Iittala)', 'Sauna & birch craft', 'Marimekko textiles', 'Reindeer-leather goods', 'Ceramics (Arabia)', 'Wool & felt', 'Juniper woodcraft'],
  DK: ['Design furniture', 'Ceramics (Royal Copenhagen)', 'Silver (Georg Jensen)', 'Wool & knitwear', 'Candles & design goods', 'Liquorice & pantry', 'Amber jewellery', 'Teak homeware'],
  NO: ['Norwegian (Selbu) knitwear', 'Rosemåling folk art', 'Pewter ware', 'Troll & woodcraft', 'Reindeer & wool goods', 'Sami duodji craft', 'Brown cheese pantry', 'Enamel jewellery'],
  IS: ['Lopapeysa wool knitwear', 'Flaky sea salt', 'Sheepskin & wool goods', 'Skyr & pantry', 'Fish-leather craft', 'Design homeware', 'Lava & Icelandic-spar jewellery'],
  PL: ['Amber jewellery', 'Bolesławiec stoneware', 'Wycinanki papercut art', 'Wooden folk crafts', 'Christmas (bombki) ornaments', 'Linen & lace', 'Pisanki painted eggs', 'Pierogi & pantry'],
  CZ: ['Bohemian crystal & glass', 'Marionette puppets', 'Garnet jewellery', 'Porcelain & ceramics', 'Wooden toys', 'Painted (kraslice) eggs', 'Beer & pantry', 'Straw & corn-husk craft'],
  SK: ['Wire art (drotárstvo)', 'Fujara flutes', 'Sheep-cheese pantry', 'Modra ceramics', 'Folk embroidery', 'Corn-husk dolls', 'Painted eggs', 'Woodcraft'],
  HU: ['Matyó & Kalocsa embroidery', 'Paprika & pantry', 'Porcelain (Herend, Zsolnay)', 'Folk ceramics', 'Tokaji wine ware', 'Leather & horse craft', 'Lace (Halas)', 'Painted eggs'],
  RO: ['Painted ceramics (Horezu)', 'Wool rugs & textiles', 'Folk (ie) embroidered blouses', 'Black pottery', 'Woodcraft & carved gates', 'Icon & glass painting', 'Merry-cemetery folk art', 'Pantry & preserves'],
  BG: ['Rose oil & rosewater', 'Troyan drip ceramics', 'Wool rugs (Chiprovtsi)', 'Embroidery & textiles', 'Martenitsa red-and-white craft', 'Copperware', 'Yogurt & pantry', 'Icon art'],
  RS: ['Opanci leather shoes', 'Wool knitwear & socks', 'Pirot kilim rugs', 'Preserves & ajvar pantry', 'Filigree jewellery', 'Rakija ware', 'Woodcraft', 'Embroidery'],
  HR: ['Lavender & essential oils', 'Cravats (necktie origin)', 'Lace (Pag, Lepoglava)', 'Licitar heart craft', 'Olive oil & pantry', 'Ceramics', 'Filigree (Morčić) jewellery', 'Wool & textiles'],
  SI: ['Painted beehive-panel art', 'Piran sea salt', 'Idrija lace', 'Kranj woodcraft', 'Honey & pantry', 'Ceramics', 'Felt & wool craft', 'Cast-iron (Kropa) ironwork'],
  UA: ['Vyshyvanka embroidery', 'Pysanky painted eggs', 'Petrykivka folk painting', 'Ceramics & pottery', 'Motanka dolls', 'Woven rushnyk cloth', 'Amber & beadwork', 'Honey & pantry'],
  BY: ['Linen goods', 'Straw-weaving art', 'Willow basketry', 'Vytsinanka papercut', 'Pottery & ceramics', 'Wool & felt', 'Wooden crafts', 'Slutsk woven silk sashes'],
  RU: ['Matryoshka dolls', 'Khokhloma painted ware', 'Gzhel blue ceramics', 'Palekh lacquer boxes', 'Orenburg lace shawls', 'Samovar & tea ware', 'Ushanka & felt (valenki)', 'Amber & malachite'],
  LT: ['Amber jewellery', 'Linen goods', 'Wool mittens & socks', 'Wooden crosses & folk art', 'Verba dried-flower craft', 'Black pottery', 'Sakotis pantry', 'Straw (sodai) ornaments'],
  LV: ['Amber jewellery', 'Wool mittens & knitwear', 'Linen textiles', 'Woodcraft', 'Ceramics', 'Rye bread & pantry', 'Folk (Lielvārde) belts', 'Herbal (Black Balsam) ware'],
  EE: ['Wool knitwear (Muhu, Kihnu)', 'Juniper woodware', 'Linen textiles', 'Leather & felt goods', 'Ceramics', 'Handmade chocolate', 'Limestone & bog craft', 'Folk jewellery'],
  MT: ['Filigree silver jewellery', 'Blown glass (Mdina)', 'Lace (bizzilla)', 'Ganutell wire flowers', 'Ceramics', 'Prickly-pear pantry', 'Maltese cross crafts', 'Gozo pottery'],
  SM: ['Collectible stamps & coins', 'Torta Tre Monti wafer cake', 'Ceramics', 'Crossbow & heraldic crafts', 'Wine & liqueur ware', 'Torrone nougat', 'Embroidered lace shawls', 'Chestnut preserves & liqueurs'],
  VA: ['Vatican postage stamps', 'Commemorative coins', 'Rosaries & devotional craft', 'Mosaic art', 'Ecclesiastical textiles', 'Papal medals'],
  MC: ['Perfume & fragrance', 'Fine jewellery', 'Ceramics & porcelain', 'Chocolate & confiserie', 'Leather goods', 'Collectible stamps', 'Glass & design craft', 'Commemorative coins'],
  AD: ['Wrought-iron craft', 'Wool & textile weaving', 'Leather goods', 'Tobacco & pantry', 'Mountain-herb craft', 'Wood carving', 'Ceramics', 'Artisan chocolate'],
  CY: ['Lefkara lace', 'Halloumi & pantry', 'Filigree silver', 'Ceramics & pottery', 'Copperware', 'Olive oil & carob', 'Basket weaving', 'Icon art'],
  AL: ['Filigree silver jewellery', 'Wool rugs (qilim)', 'Carved walnut woodwork', 'Copperware', 'Traditional (qeleshe) felt caps', 'Embroidery', 'Raki & pantry', 'Opinga traditional shoes'],
  MK: ['Ohrid pearls', 'Filigree jewellery', 'Copperware', 'Wool rugs & textiles', 'Ceramics', 'Icon & fresco art', 'Ajvar & pantry', 'Handwoven kilim rugs'],
  BA: ['Copper coffee sets & trays', 'Bosnian rugs (ćilim)', 'Filigree jewellery', 'Woodcraft', 'Handwoven textiles', 'Preserves & pantry', 'Leather goods', 'Konjic hand-carved woodwork'],
  ME: ['Olive oil & pantry', 'Wool rugs & textiles', 'Filigree jewellery', 'Ceramics', 'Embroidery', 'Woodcraft', 'Honey & rakija ware', 'Njeguški prosciutto'],
  MD: ['Wool rugs & carpets', 'Ceramics & pottery', 'Embroidered (ie) textiles', 'Preserves & wine ware', 'Willow basketry', 'Woodcraft', 'Hand-woven wall carpets', 'Martisor brooches'],
  // The Americas
  MX: ['Talavera pottery', 'Barro negro (black clay)', 'Embroidered huipiles', 'Copper (Santa Clara) pans', 'Alebrijes', 'Molcajetes', 'Taxco silver jewellery', 'Otomí textiles'],
  GT: ['Backstrap-woven huipiles', 'Jade jewellery', 'Antigua coffee', 'Worry dolls', 'Ceramics & pottery', 'Beaded crafts', 'Wool blankets', 'Wood & mask carving'],
  PE: ['Alpaca knitwear & throws', 'Silver & filigree jewellery', 'Andean handwoven textiles', 'Chullo hats', 'Retablo folk art', 'Chulucanas ceramics', 'Pima cotton goods', 'Woven belts & bags'],
  BO: ['Alpaca throws & knitwear', 'Aguayo woven textiles', 'Silver jewellery', 'Salt-flat & mineral craft', 'Ceramics & pottery', 'Woven hats & bags', 'Wood carving', 'Coca & pantry'],
  EC: ['Panama hats (Montecristi)', 'Single-origin cacao', 'Tagua nut carving', 'Otavalo woven textiles', 'Roses & floral craft', 'Balsa-wood birds', 'Silver (Chordeleg) filigree', 'Leather goods'],
  CO: ['Coffee', 'Wayuu mochila bags', 'Emerald jewellery', 'Filigree (Mompox) silver', 'Sombrero vueltiao hats', 'Leather goods', 'Ceramics (La Chamba)', 'Cacao & pantry'],
  BR: ['Coffee', 'Gemstone jewellery', 'Havaianas & leather goods', 'Hammocks', 'Capim-dourado golden-grass craft', 'Cachaça & pantry', 'Carnival craft', 'Wood & berimbau instruments'],
  AR: ['Leather goods & saddlery', 'Mate gourds & bombillas', 'Ponchos & woven textiles', 'Silver (facón & rastra) craft', 'Wine & pantry', 'Alpargata shoes', 'Rhodochrosite jewellery', 'Dulce de leche pantry'],
  CL: ['Lapis lazuli jewellery', 'Copper homeware', 'Mapuche silver & textiles', 'Wine & pantry', 'Combarbalita stone craft', 'Chamanto woven cloth', 'Ceramics (Pomaire)', 'Wool crafts'],
  UY: ['Wool throws & knitwear', 'Mate gourds & ware', 'Leather goods', 'Amethyst & agate jewellery', 'Ceramics', 'Dulce de leche pantry', 'Woven textiles', 'Alfajores'],
  PY: ['Ñandutí lace', "Ao po'i embroidered cotton", 'Silver (Luque) filigree', 'Leather goods', 'Yerba mate & pantry', 'Wood carving', 'Ceramics', 'Woven hammocks'],
  VE: ['Single-origin cacao & chocolate', 'Woven hammocks', 'Wayuu textiles & bags', 'Coffee & pantry', 'Tapara gourd craft', 'Ceramics', 'Rum & pantry', 'Beaded jewellery'],
  GY: ['Tibisiri straw baskets', 'Amerindian woven craft', 'Balata-rubber figures', 'Wood carving', 'Cassava & pantry', 'Beaded jewellery', 'Pottery', 'Amerindian cotton hammocks'],
  SR: ['Maroon (Tembe) wood carving', 'Hand-woven hammocks', 'Javanese batik textiles', 'Amerindian basketry', 'Beaded jewellery', 'Cassava & pantry', 'Coconut craft', 'Koto traditional dress'],
  BS: ['Androsia batik textiles', 'Straw-plaited goods', 'Rum & pantry', 'Junkanoo festival craft', 'Coconut craft', 'Inagua sea salt', 'Guava duff preserves', 'Lignum vitae wood carvings'],
  CU: ['Guayabera shirts', 'Cigars & tobacco craft', 'Coffee', 'Rum & pantry', 'Leather goods', 'Papier-mâché & folk art', 'Straw hats', 'Percussion instruments'],
  DO: ['Larimar jewellery', 'Blue amber', 'Cacao & chocolate', 'Cigars', 'Coffee & pantry', 'Faceless (Limé) dolls', 'Mahogany carving', 'Woven baskets'],
  GD: ['Nutmeg & spice pantry', 'Cacao & chocolate', 'Spice-blend crafts', 'Rum & pantry', 'Woven baskets'],
  LC: ['Coal-pot clay cookware', 'Woven straw baskets', 'Cacao & chocolate', 'Batik & madras textiles', 'Coconut & calabash craft', 'Hot sauce & pantry', 'Wood carvings', 'Cocoa sticks (cocoa tea)'],
  DM: ['Kalinago larouma-reed baskets', 'Carved calabash art', 'Bay-leaf oil & pantry', 'Coconut & vetiver craft', 'Cocoa & pantry', 'Woven mats', 'Bay rum soap and cologne', 'Single-origin chocolate bars'],
  KN: ['Caribelle batik textiles', 'Coconut-shell craft', 'Sugar & rum pantry', 'Woven baskets', 'Pottery', 'Wood carvings', 'Cane sugar cakes', 'Kittitian hot pepper sauce'],
  AG: ['Redware pottery', 'Woven baskets', 'Rum & pantry', 'Batik textiles', 'Coconut craft', 'Sea-glass jewellery', 'Guava cheese preserves'],
  VC: ['Woven baskets & mats', 'Wood & model-boat carving', 'Arrowroot & pantry', 'Handcrafted jewellery', 'Coconut craft', 'Batik textiles', 'Straw hats & slippers'],
  HT: ['Steel-drum (fer découpé) art', 'Vetiver oil', 'Papier-mâché art', 'Vibrant folk painting', 'Sisal & straw craft', 'Wood carving', 'Beaded (Vodou flag) art', 'Cacao & pantry'],
  JM: ['Blue Mountain coffee', 'Jerk spice & pantry', 'Wood carving', 'Rum & pantry', 'Beaded & seed jewellery', 'Straw & bamboo craft', 'Bark (lignum vitae) craft'],
  TT: ['Steelpan instruments', 'Fine cacao & chocolate', 'Carnival (mas) craft', 'Leather & calabash craft', 'Angostura & pantry', 'Beaded jewellery', 'Coconut craft', 'Trinidad rum'],
  BB: ['Chalky Mount pottery', 'Mahogany carving', 'Rum & pantry', 'Rum cakes', 'Batik textiles', 'Blackbelly-wool crafts', 'Straw-woven baskets and hats', 'Bajan pepper sauce'],
  CA: ['Maple syrup & pantry', "Wool (Hudson's Bay) blankets", 'Inuit soapstone carving', 'Ice-wine ware', 'Beaded & birchbark craft', 'Smoked salmon pantry', 'Cowichan knitwear', 'Amethyst & jade'],
  US: ['Workwear denim', 'Craft leather goods', 'Hot sauce & pantry', 'Bourbon & barrel craft', 'Quilts & Americana', 'Turquoise & Native silver', 'Cast-iron cookware', 'Maple & pantry'],
  CR: ['Painted oxcart (carreta) craft', 'Coffee', 'Ceramics (Chorotega)', 'Wood & cocobolo carving', 'Leather goods', 'Cacao & pantry', 'Coffee-wood crafts', 'Boruca ceremonial masks'],
  PA: ['Mola reverse-appliqué textiles', 'Geisha coffee', 'Panama hats (sombrero pintao)', 'Tagua-nut carving', 'Ceramics', 'Beaded (chaquira) craft', 'Cocobolo woodcraft', 'Cutarras leather sandals'],
  NI: ['Woven hammocks', 'Coffee', 'Ceramics (San Juan de Oriente)', 'Primitivist (Solentiname) art', 'Leather & rosewood craft', 'Palm & straw weaving', 'Nicaraguan cigars', 'San Juan de Oriente pottery'],
  HN: ['Lenca pottery', 'Coffee', 'Junco-palm weaving', 'Mahogany wood carving', 'Corn-husk crafts', 'Leather goods', 'Cigars & pantry', 'Honduran hammocks'],
  SV: ['Indigo (añil) textiles', 'La Palma folk painting', 'Volcanic coffee', 'Ceramics & pottery', 'Woven hammocks', 'Handloom cotton', 'Wood crafts', 'Ilobasco ceramic sorpresas'],
  BZ: ['Cacao & chocolate', 'Hot (habanero) sauce', 'Slate & Maya carving', 'Woven baskets', 'Coconut & shell craft', 'Jippi-jappa weaving', 'Coffee & pantry', 'Garifuna drums'],
  // Oceania
  AU: ['Merino wool knitwear', 'Eucalyptus & manuka honey', 'Aboriginal dot-painting art', 'Opal jewellery', 'Sheepskin (ugg) goods', 'Tea-tree & bush skincare', 'Leather (Akubra) hats', 'Boomerang & didgeridoo craft'],
  NZ: ['Mānuka honey', 'Merino & possum knitwear', 'Pounamu (greenstone) carving', 'Māori bone (hei-tiki) carving', 'Wool blankets & sheepskin', 'Kauri-wood craft', 'Flax (harakeke) weaving', 'Wine & pantry'],
  FJ: ['Masi (tapa) bark cloth', 'Kava & pantry', 'Coconut-oil skincare', 'Woven (voivoi) mats & baskets', 'Sandalwood craft', 'Pearl jewellery', 'Wood (tanoa) carving'],
  WS: ['Siapo bark cloth', 'Fine (ie toga) mat weaving', 'Coconut oil & skincare', 'Kava (ava) ware', 'Wood (tanoa) carving', 'Seed jewellery', 'Tattoo-motif crafts'],
  TO: ['Ngatu (tapa) bark cloth', 'Pandanus mat weaving', 'Coconut & shell craft', 'Bone & wood carving', 'Woven baskets', 'Kava ware', 'Tapa-motif crafts', 'Kie hingoa fine mats'],
  KI: ['Pandanus woven mats', 'Coconut-fibre (sennit) craft', 'Woven baskets', 'Wood carving', 'Salt & pantry', 'Carved model outrigger canoes'],
  TV: ['Kolose crochet craft', 'Pandanus & coconut-leaf weaving', 'Woven fans & baskets', 'Coconut craft', 'Wood carving', 'Woven pandanus mats'],
  PG: ['Bilum string bags', 'Sepik wood & mask carving', 'Coffee', 'Woven baskets & mats', 'Bark-cloth craft', 'Clay pottery'],
  SB: ['Wood carving (nguzunguzu)', 'Woven baskets & mats', 'Coconut craft', 'Kastom textiles', 'Nut-inlay bowls', 'Nguzu nguzu canoe prow carvings', 'Hand-carved wooden ceremonial bowls', 'Panpipes'],
  VU: ['Wood carving (slit-drums)', 'Woven (pandanus) mats & baskets', 'Sand-drawing art', 'Tamtam craft', 'Coconut craft', 'Kava & pantry', 'Tapa cloth', 'Grass skirts'],
}

export function cultureHints(code: string): string[] {
  return CULTURE_HINTS[code] ?? []
}
